# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quadratic.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'quadratic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fquadratic.proto\x12\tquadratic\"3\n\x10QuadraticRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"\"\n\x11QuadraticResponse\x12\r\n\x05roots\x18\x01 \x03(\x01\x32^\n\x0fQuadraticSolver\x12K\n\x0eSolveQuadratic\x12\x1b.quadratic.QuadraticRequest\x1a\x1c.quadratic.QuadraticResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUADRATICREQUEST']._serialized_start=30
  _globals['_QUADRATICREQUEST']._serialized_end=81
  _globals['_QUADRATICRESPONSE']._serialized_start=83
  _globals['_QUADRATICRESPONSE']._serialized_end=117
  _globals['_QUADRATICSOLVER']._serialized_start=119
  _globals['_QUADRATICSOLVER']._serialized_end=213
# @@protoc_insertion_point(module_scope)
